---
# tasks file for prodsrv
 - name: install packages
   apt:
     name:
      - tomcat9
      - rsync
     state: present
     update_cache: yes

 - name: transfer war file from dev
   synchronize:
    src: "{{ src_folder }}/{{ src_file }}"
    dest: "{{ dest_folder }}"
   delegate_to: "{{ src_server }}"
   notify: start tomcat9
     