---
# tasks file for devsrv
 - name: install packages   
   apt:
     name:
      - git
      - maven
      - rsync
     state: present
     update_cache: yes
 

 - name: Clone a github repository
   git:
    repo: "{{ app_repo }}"
    dest: "{{ app_folder }}"
    clone: yes
    update: yes

 - name: Maven package create
   command: mvn -f "{{ app_folder }}"/pom.xml package -DskipTest