---
# tasks file for devsrv
 - name: install packages
   apt: pkg= {{ item }} state=present update_cache=yes
   with_items:
       - git
       - maven

 - name: Clone a github repository
   git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: /usr/share/app-src
    clone: yes
    update: yes

 - name: Maven package create
   command: mvn -f /usr/share/app-src/pom.xml package -DskipTest