---
# tasks file for devsrv
 - name: install packages
   apt: pkg= {{ item }} state=present update_cache=yes
   with_items:
       - git
       - maven

 - name: Clone a github repository
   git:
    repo: {{ app_repo }}
    dest: {{ app_folder }}
    clone: yes
    update: yes

 - name: Maven package create
   command: mvn -f {{ app_folder }}/pom.xml package -DskipTest